### ISSUE TITLE
setup/requirements.txt is missing

### ISSUE THREAD

**Issue by yurakuratov** [stanford-crfm/pubmedgpt#1]
Hi! Seems like requirements.txt from installing [instructions](https://github.com/stanford-crfm/pubmedgpt/tree/main/finetune#dependencies) is missing in the repo.

**Comment by J38** [comment]
Okay I fix this thanks for letting me know!

**Comment by gerardsimons** [comment]
Fixed how? I still do not see requirements or setup.py?
