### ISSUE TITLE
Can you share preprocessed datasets for fine-tuning?

### ISSUE THREAD

**Issue by Nardien** [stanford-crfm/pubmedgpt#5]
Thank you for open-sourcing this valuable resource. I am interested in reproducing the experiments in this repository and would like to follow the fine-tuning setup you used.

However, I noticed that the data folders for the fine-tuning tasks do not contain the datasets. Could you please share the preprocessed datasets or provide guidelines on how to preprocess the data for the reproduction of the results?

I would greatly appreciate any assistance you can provide.

**Comment by J38** [comment]
Sure thing I will add more details about how to do that and some helper scripts.

**Comment by Nardien** [comment]
Thanks a lot!! Please close this issue if you finish the work.

**Comment by J38** [comment]
I have added some basic instructions for getting MedQA, PubMedQA, and BioASQ running. There are  preprocessing scripts in `finetune/mc` and `finetune/seqcls` . You do need to go to the original sources for these tasks to download the original data. Then you can run the preprocessing scripts and it will produce the one example per line .jsonl that is expected.

I haven't really tested out rebuilding this data, so please let me know if you encounter any issues or if anything is unclear and I will update the scripts and instructions !

**Comment by evanbrociner** [comment]
Are there pre trained weights for the MedQA or PubMedQA fine-tuned model. Thank you!

**Comment by J38** [comment]
We didn't save the fine-tuned models for the tasks. There are some upcoming conference deadlines so our compute is really busy at this time, but when it frees up I intend to work on re-doing the fine-tuning and saving the models this time and we can make those available.

**Comment by evanbrociner** [comment]
No problem, thank you so much!

**Comment by Nardien** [comment]
Thank you for the quick update! I have checked that preprocessing codes on PubMedQA and MedQA work well, and successfully fine-tuned the GPT2 model on both datasets. (Unfortunately, my computation resources also cannot handle PubMedGPT fine-tuning...)

Regarding BioASQ, I fail to find appropriate raw dataset files in tsv format on its [official homepage](http://www.bioasq.org/).
I found there is a [GitHub repo](https://github.com/dmis-lab/bioasq-biobert) providing a preprocessed version of BioASQ, but I am not sure this is the same version that you used in your experiments.
If it's okay, can you share more details on the BioASQ dataset you used in experiments?

Thanks again for your kind and responsive comment!

**Comment by Nardien** [comment]
++ Update

I found that LinkBERT offers detailed [preprocessing scripts](https://github.com/michiyasunaga/LinkBERT/blob/main/scripts/download_raw_data.sh) for bioasq following BLURB benchmark!

It seems that this repo also utilizes the same preprocessing pipeline with LinkBERT. So I will try it.

**Comment by J38** [comment]
Yes I directly copied those scripts into this repo as well in `finetune/seqcls` and `finetune/mc`

**Comment by J38** [comment]
Did I miss anything when copying over? I did delete the non-QA stuff for now ... though technically people might want that too ... we haven't focused on the full BLURB yet ...

**Comment by J38** [comment]
@michiyasunaga who created LinkBERT is one of the team members on this project as well ...

**Comment by Nardien** [comment]
At least for bioasq, I think people need following codes from the BLURB benchmark.

```
wget https://microsoft.github.io/BLURB/sample_code/data_generation.tar.gz
tar -xf data_generation.tar.gz
```

In the downloaded codes, there is a preprocessing code (`preprocessor.py`) containing bioasq preprocessing, which parses `BioASQ-training7b/trainining7b.json` and `Task7BGoldenEnriched` into `train.tsv`, `dev.tsv`, and `test.tsv` files.
(Note that `BioASQ-training7b/trainining7b.json` and `Task7BGoldenEnriched` are files that can be downloaded from the official [bioasq homepage](http://participants-area.bioasq.org/datasets/) - Datasets for task b - BioASQ7.)

With the preprocessed `*.tsv` files, I can finally get the jsonl files using [the preprocessing code in this repo](https://github.com/stanford-crfm/pubmedgpt/blob/main/finetune/seqcls/preprocess_blurb_seqcls.py).

I think adding the above information to this repo might be helpful for future practitioners!

**Comment by J38** [comment]
Sounds good ... the scripts from LinkBERT are exactly what we used for this ...

**Comment by evanbrociner** [comment]
@Nardien any chance you can share the weights of the fine-tuned model? Thank you
